Add version constraint for symfony/config and zenstruck/foundry
Support for Enum cases in the configuration was added in symfony/config:6.3
https://github.com/symfony/symfony/commit/1655d1763ba210b5f7d632e4e36b1f814fd30038

Error: Object of class Zenstruck\Foundry\ORM\ResetDatabase\ResetDatabaseMode could not be converted to string

/home/runner/work/ux/ux/src/LiveComponent/vendor/symfony/config/Definition/Builder/EnumNodeDefinition.php:30
/home/runner/work/ux/ux/src/LiveComponent/vendor/zenstruck/foundry/src/ZenstruckFoundryBundle.php:152